name: journo
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


#--------------- PACKAGES ---------------#
dependencies:
  flutter:
    sdk: flutter


  # Utility Packages
  flutter_native_splash: ^2.4.1
  intl: ^0.19.0
  smooth_page_indicator: ^1.2.0+3





  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8


  #--------------- PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  #--------------- LOCAL ASSETS ---------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/animations/


    #--------------- LOCAL FONTS ---------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic   #CHECK
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300   #CHECK
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
